services:
  kali-htb:
    image: kalilinux/kali-rolling
    container_name: kali-htb
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./htb_machines:/root/htb_machines
      - ./.bash_history:/root/.bash_history
      - ./entrypoint.sh:/entrypoint.sh     
    environment:
      - TZ=Europe/Madrid
    env_file:
      - .env
    entrypoint: ./entrypoint.sh
    command: /bin/bash
    restart: unless-stopped
    networks:
      - kali_net

networks:
  kali_net:
    driver: bridge